

SET LANGUAGE 'us_english'
GO

select * from cliente

select * from IMOVEL

CREATE DATABASE Imobiliaria

CREATE TABLE CLIENTE(
	COD_CLIENTE INT PRIMARY KEY IDENTITY ,
	NOME VARCHAR (25) NOT NULL,
	SOBRENOME VARCHAR (40) NOT NULL,
	EMAIL VARCHAR (50) NOT NULL,
	SENHA VARCHAR (15) NOT NULL)
	
	
CREATE TABLE IMOVEL(
	COD_IMOVEL INT PRIMARY KEY IDENTITY ,
	TIPO_CONTRATO VARCHAR (7) NOT NULL,
	TIPO_IMOVEL VARCHAR (11) NOT NULL,
	NUMERO_COMODOS INT,
	AREA_TERRENO INT,
	PREÇO MONEY NOT NULL,
	DESCRICAO VARCHAR (200),
	DATA_INCLUSAO DATETIME)
	
	
	
INSERT INTO CLIENTE VALUES ('ROGERIO' , 'TROVIJO' , 'rogerio.trovijo@fatec.sp.gov.br' , '123456')

INSERT INTO IMOVEL VALUES ('COMPRA' , 'CASA' , 5 , '' , 100000 , 'IMOVEL NOVO EM INDAIATUBA' , GETDATE())

INSERT INTO IMOVEL VALUES ('ALUGUEL' , 'APARTAMENTO' , 4 , '' , 1200 , 'VALOR DO CONDOMINIO R$ 250,00 NÃO INCLUSO' , GETDATE())

INSERT INTO IMOVEL VALUES ('COMPRA' , 'TERRENO' , '' , 300 , 150000 , 'TERRENO EM ÓTIMA LOCALIZAÇÃO DA CIDADE' , GETDATE())

INSERT INTO IMOVEL VALUES ('COMPRA' , 'CHACARA' , '' , 2000 , 450000 , 'CHACARA COM POMAR FORMADO' , GETDATE())

INSERT INTO IMOVEL VALUES ('ALUGUEL' , 'COMERCIAL' , 10 , '' , 5000 , 'GALPÃO NO DISTRITO INDUSTRIAL' , GETDATE())
	
	
	
	

